schema_version: 1
reference_id: grch38
sample_id: HG002

truthsets:
  giab_hg002_grch38_v5_0q:
    role: primary
    truth_status: draft
    release: v5.0q
    reference_id: grch38
    sample_id: HG002
    source_page: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/GRCh38/
    files:
      vcf:
        name: HG002_GRCh38_v5.0q_stvar.vcf.gz
        local_path: resources/truth/giab_hg002_grch38_v5_0q/HG002_GRCh38_v5.0q_stvar.vcf.gz
        sha256: d66b2d2496ff5418763813d3195599007dbff950514d10e5bc27b6c8b76e34b8
      vcf_index:
        name: HG002_GRCh38_v5.0q_stvar.vcf.gz.tbi
        local_path: resources/truth/giab_hg002_grch38_v5_0q/HG002_GRCh38_v5.0q_stvar.vcf.gz.tbi
        sha256: 57898d17e44ecd5c286aeb863f27e613244396a3ad4b04ca79c8add647b8a81d
      benchmark_bed:
        name: HG002_GRCh38_v5.0q_stvar.benchmark.bed
        local_path: resources/truth/giab_hg002_grch38_v5_0q/HG002_GRCh38_v5.0q_stvar.benchmark.bed
        sha256: 2f75ce942e1dd9e1a443e4e04facc640104aae5e23fba24d7d3f2c1f1f9985b00
    filters:
      pass_only: true
      inside_benchmark_bed: true
      region_policy: fully_contained
      minimum_sv_size: 50
      allowed_svtypes: [DEL, INS]
      reject_multiallelic_sv: true
      multiallelic_policy: exclude
    required_sha256_before_execution: true
